{% set version = "1.6.4" %}

package:
  name: windrose
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/windrose/windrose-{{ version }}.tar.gz
  sha256: 540b3dcb8a0cb62e549e1e82019e591c30f04e9794b21a5a456f1c9adff433cb
  patches:
    - no_setuptools-markdown.patch

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - matplotlib
    - numpy

test:
  imports:
    - windrose

about:
  home: https://github.com/python-windrose/windrose
  license: CeCILL-2.1
  # license_file: LICENCE
  summary: 'Python Matplotlib, Numpy library to manage wind data, draw windrose.'

extra:
  recipe-maintainers:
    - ocefpaf
